### ISSUE TITLE
Handle incorrect zoom level (and other values)

### ISSUE THREAD

**Issue by miloskroulik** [kartena/printlet#10]
If I enter incorrect zoom level as part of URL in server.js mode, Printlet is trying to display image for a while, then failing silently. It would be useful, if image useful for debugging was generated instead (with message such as `Entered zoom value exceeds maxzoom property defined in your tileJSON file. Please enter correct value and try again`

Similar checks would be probably also useful for other properties.

**Comment by icetan** [comment]
The purpose of the `server.js` file is to be an example of how to integrate the `printlet` lib as a REST service.

The lib itself will not check for correct zoom levels and will not throw an error when a tile fails to load due to the possibility that the requested tiles might intersect with both correct and incorrect tile coordinates and there must still be a result. It is up to the code calling `printlet` lib to make sure that the arguments passed are sane.

Iv'e added a small check (kartena/printlet@8cc0d58) to illustrate how to handle incorrect parameters and return a HTTP 400 code. This will enable the client to handle the exception correctly. But this code should not be thought of as part of `printlet` it is to serve as an example, but you are welcome to use it as a starting point of course.
