### ISSUE TITLE
Format text

### ISSUE THREAD

**Issue by miloskroulik** [kartena/printlet#7]
First, thanks for Printlet, seems very useful. I would like to format rendered text somehow, so it would be possible to use renders in more design-oriented projects.

**Comment by icetan** [comment]
Sorry for my late reply and thank you for checking out printlet.

It is possible to add text markers to point features and also style and offset the text. Because the styling follows the HTML5 canvas API you can use the `font` and `fillStyle` properties in the `style` object to format text. Read more about styling text with HTML5 canvas [here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text#Styling_text) and a brief example from the [readme](https://github.com/kartena/printlet#drawing-geojson-features).

I have updated  [examples/static.js](https://github.com/kartena/printlet/blob/master/examples/static.js) in the repository to demonstrate. Run `node examples/static.js` from the project root directory and the result should be in `image.png` when the command has finished.

**Comment by miloskroulik** [comment]
Thanks, it works nicely.
